#!/bin/zsh

COLOR_WHITE='\033[0;37m'
COLOR_B_PURPLE='\033[1;35m'
COLOR_DEFAULT='\033[0m'

function logger {
    echo -e "${COLOR_B_PURPLE}[drosh:dotfiles]:${COLOR_WHITE} $1${COLOR_DEFAULT}"
}

logger "Creating symlinks for vim, zsh and git..."

# mkdir -p $HOME/.config/nvim
ln -sf $(pwd)/nvim $HOME/.config

ln -sf $(pwd)/src/bashrc $HOME/.bashrc
ln -sf $(pwd)/src/gitconfig $HOME/.gitconfig
ln -sf $(pwd)/src/zpreztorc $HOME/.zpreztorc
ln -sf $(pwd)/src/zshrc $HOME/.zshrc
# ln -sf $(pwd)/src/vimrc_background $HOME/.vimrc_background
# ln -sf $(pwd)/src/tmux.conf $HOME/.tmux.conf

logger "Installing vim-plug and do PlugInstall..."
nvim

DEFAULT_THEME=base16_tomorrow-night
logger "Try to set ${DEFAULT_THEME}"
eval $DEFAULT_THEME

logger "Job's done! ;)"
