# fzf (fd install via brew)
export FZF_DEFAULT_COMMAND='fd --hidden --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# install via .pkg from https://github.com/Homebrew/brew/releases
eval "$(/opt/homebrew/bin/brew shellenv)"
# install via brew
eval "$(fzf --zsh)"

alias vim="nvim"

# disable autocorrect
unsetopt correct_all

# nvm
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
    [ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && . "$(brew --prefix)/opt/nvm/nvm.sh" # This loads nvm
    [ -s "$(brew --prefix)/opt/nvm/etc/bash_completion" ] && . "$(brew --prefix)/opt/nvm/etc/bash_completion" # This loads nvm bash_completion

# set default Python 3
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
fi

# go
export PATH="/Users/drosh/go/bin:$PATH"

# use make from brew
# see more https://formulae.brew.sh/formula/make
PATH="$HOMEBREW_PREFIX/opt/make/libexec/gnubin:$PATH"

# The next line updates PATH for Yandex Cloud CLI.
if [ -f '/Users/drosh/yandex-cloud/path.bash.inc' ]; then source '/Users/drosh/yandex-cloud/path.bash.inc'; fi

# The next line enables shell command completion for yc.
if [ -f '/Users/drosh/yandex-cloud/completion.zsh.inc' ]; then source '/Users/drosh/yandex-cloud/completion.zsh.inc'; fi

alias ycs3="aws --endpoint-url=https://storage.yandexcloud.net s3"
alias ycs3api="aws --endpoint-url=https://storage.yandexcloud.net s3api"
[[ "$PATH" == *"$HOME/bin:"* ]] || export PATH="$HOME/bin:$PATH"
! { which werf | grep -qsE "^/Users/drosh/.trdl/"; } && [[ -x "$HOME/bin/trdl" ]] && source $("$HOME/bin/trdl" use werf "1.2" "stable")

# kubectl krew
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# psql
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/drosh/miniforge3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/drosh/miniforge3/etc/profile.d/conda.sh" ]; then
        . "/Users/drosh/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/drosh/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/Users/drosh/miniforge3/etc/profile.d/mamba.sh" ]; then
    . "/Users/drosh/miniforge3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source /Users/drosh/yandex-cloud/completion.zsh.inc

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/drosh/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/drosh/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/drosh/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/drosh/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
